# Generated by Django 4.2.1 on 2023-09-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_section',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
