# Generated by Django 4.2.1 on 2023-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0002_catalog_section_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
