# Generated by Django 4.2.1 on 2023-09-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0003_alter_product_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog_section',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
