# Generated by Django 4.2.1 on 2023-10-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0005_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
